// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeriodicTableTutor.Data;

#nullable disable

namespace PeriodicTableTutor.Migrations
{
    [DbContext(typeof(ElementModelContext))]
    [Migration("20240420110338_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PeriodicTableTutor.Models.ElementModel", b =>
                {
                    b.Property<int>("AtomicNumber")
                        .HasColumnType("int");

                    b.Property<double>("Density")
                        .HasColumnType("float");

                    b.Property<string>("LatinName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MassNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Neutrons")
                        .HasColumnType("int");

                    b.Property<int>("Protons")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearOfDiscover")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Elements");
                });
#pragma warning restore 612, 618
        }
    }
}
